# Generated by Django 5.2.5 on 2025-08-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=2, help_text='Rating out of 5.0', max_digits=3)),
                ('publication_year', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['book_id'],
            },
        ),
    ]
